Update patch set 2
Patch Set 2: Code-Review-1

This broke the build for me in 8.1 tree (I am not specifying this flag in BoardConfig):

bootable/recovery/gui/gui.cpp:775:9: error: use of undeclared identifier 'TW_DELAY_TOUCH_INIT_MS
        usleep(TW_DELAY_TOUCH_INIT_MS);
               ^
1 error generated.

Patch-set: 2
Reviewer: Gerrit User 32 <32@9c1c7d72-6534-4d44-b0ea-39f63e804833>
Label: Code-Review=-1