Is_Mounted: fix symlink detection
this will also fix an issue when using f2fs repair/format which sometimes occurs.

note:
for reproducing it is important using f2fs as first / only partition file system on userdata.
only then the format button would try to format with F2FS at all.

related repair error:

> Repairing Data using fsck.f2fs...
> I:Repair command: /sbin/fsck.f2fs /dev/block/mmcblk0p50
> Info: Mounted device!
> 	Error: Not available on mounted device!
> /sbin/fsck.f2fs /dev/block/mmcblk0p50 process ended with ERROR: 255
> Unable to repair Data.

related format error:

> Formatting Data using mkfs.f2fs...
> I:Using newer mkfs.f2fs
> I:mkfs.f2fs command: mkfs.f2fs -d1 -f -O encrypt -O quota -O verity -w 4096 /dev/block/mmcblk0p50 6078464 && sload.f2fs -t /data /dev/block/mmcblk0p50
>
> 	F2FS-tools: mkfs.f2fs Ver: 1.10.0 (2018-01-30)
>
> Info: Disable heap-based policy
> Info: Debug level = 1
> Info: Label =
> Info: Trim is enabled
> Info: Mounted device!
> 	Error: Not available on mounted device!
> mkfs.f2fs -d1 -f -O encrypt -O quota -O verity -w 4096 /dev/block/mmcblk0p50 6078464 && sload.f2fs -t /data /dev/block/mmcblk0p50 process ended with ERROR: 255
> Unable to wipe Data.
> Unable to format to remove encryption.

Change-Id: Ic941b1e54476d9510fbf4a51d19b4d21f2e0426b
(cherry picked from commit eca1e6d9c04c23042e95a9d7eff2d6ecebd15817)